#Receita de Miojo do pirata
print("Pegar uma panela")
print("Colocar a água pra ferver na panela")
print("Colocar o miojo pra ferver")
print("Esperar ficar no ponto ideal")
print("Colocar o tempero")
print("Mexer o miojo")
print("Desligar o fogo")
print("Pegar um prato")
print("Colocar o miojo no prato")